### ISSUE TITLE
Share Result not working on high bandwidth

### ISSUE THREAD

**Issue by ZordoPlayz** [sivel/speedtest-cli#482] opened 2018-02-15 07:51 UTC
Proof:
```
Retrieving speedtest.net configuration...
Testing from Strato AG (***.***.***.***)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by SysEleven GmbH (Berlin) [1.13 km]: 1.506 ms
Testing download speed................................................................................
Download: 5968.96 Mbit/s
Testing upload speed................................................................................................
Upload: 102.77 Mbit/s
Share results: http://www.speedtest.net/result/0.png
```

```
Retrieving speedtest.net configuration...
Testing from Strato AG (***.***.***.***)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by SysEleven GmbH (Berlin) [1.13 km]: 1.518 ms
Testing download speed................................................................................
Download: 6124.65 Mbit/s
Testing upload speed................................................................................................
Upload: 101.49 Mbit/s
Share results: http://www.speedtest.net/result/0.png
```

All of the above test are made with the newest version fetched from this repository.

**Comment by sivel** [comment] 2018-02-15 14:57
Duplicate of https://github.com/sivel/speedtest-cli/issues/241

**Closed by sivel** 2018-02-15 14:57 UTC

**Comment by thexzan** [comment] 2018-06-23 10:58
just install the latest version and this issue is still here.

`Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from ******
Selecting best server based on latency...
Hosted by Viewqwest Pte Ltd (Singapore) [6.25 km]: 1.743 ms
Testing download speed........................................
Download: 3786.83 Mbit/s
Testing upload speed..................................................
Upload: 186.73 Mbit/s
Share results: http://www.speedtest.net/result/0.png`
