### ISSUE TITLE
speedtest cli list only show certain server list

### ISSUE THREAD

**Issue by hendranata** [sivel/speedtest-cli#718] opened 2020-04-07 00:40 UTC
helo
just this week i realized that speedtest-cli only show several server around asia.
i check us and Europe does not exist there..

any idea why?

**Comment by msoayu56** [comment] 2020-04-07 00:54
true. only nearest 1k server

**Comment by hendranata** [comment] 2020-04-07 00:54
how do we list all around the world?

**Comment by msoayu56** [comment] 2020-04-07 01:13
here's a html list. https://web.archive.org/web/20200307234136/https://telcodb.net/explore/speedtest-servers/#

**Comment by hendranata** [comment] 2020-04-07 01:18
yes. but when i try:
speedtest-cli --server 9056
it does not work anymore right now.

**Comment by hendranata** [comment] 2020-04-07 01:20
speedtest-cli --server 9056
Retrieving speedtest.net configuration...
Testing from xx (x.x.x.x)...
Retrieving speedtest.net server list...
ERROR: No matched servers: 9056

**Comment by hendranata** [comment] 2020-04-07 12:03
no idea?

**Comment by sivel** [comment] 2020-04-07 16:22
Duplicate of https://github.com/sivel/speedtest-cli/issues/717

**Closed by sivel** 2020-04-07 16:22 UTC
