### ISSUE TITLE
"Hosted by"-string printed as b'Hosted by...'

### ISSUE THREAD

**Issue by tomvanderlee** [sivel/speedtest-cli#192] opened 2015-10-09 16:49 UTC
So I was speedtesting my connection when I noticed something weird

    Retrieving speedtest.net configuration...
    Retrieving speedtest.net server list...
    Testing from Ziggo (ip here)...
    Selecting best server based on latency...
    b'Hosted by SoftLayer Technologies, Inc. (Amsterdam) [32.92 km]: 15.53 ms'
    Testing download speed........................................
    Download: 68.76 Mbit/s
    Testing upload speed..................................................
    Upload: 12.13 Mbit/s

The "Hosted by"-string is printed as `b'Hosted by...'`.

     b'Hosted by SoftLayer Technologies, Inc. (Amsterdam) [32.92 km]: 15.53 ms'

This has to do with the UTF-8 encoding as shown in this snippet:

     >>> print(("test".encode('UTF-8')))
     b'test'

**Comment by tianon** [comment] 2016-01-30 05:46
I'm seeing this consistently too (Python 3.4.3 in Alpine Linux).

@maride any reason you didn't make 81fa7c5 into a PR? :smile:  (does it not appropriately fix the issue?)

I also see the issue when I do `--list`:
```console
$ speedtest-cli --list
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
b'6412) T-Mobile (North Las Vegas, NV, United States) [7.52 km]\n1431) Switch (Las Vegas, NV, United States) [12.67 km]\n....'
```

**Comment by tianon** [comment] 2016-01-30 05:52
A little less esoteric place I can reproduce easily is Python 3.5.1 from Debian Unstable (installing `python3-pip` and then doing `pip3 install speedtest-cli`).

**Comment by tianon** [comment] 2016-01-30 05:57
Sorry if this is already obvious (I'll admit openly that my Python-fu is subpar), but it appears that this is caused by the fact that in Python 2, `str.encode` returns a "string" (https://docs.python.org/2/howto/unicode.html - "which returns an 8-bit string version of the Unicode string") vs Python3 `str.encode` which returns a "bytes object" (https://docs.python.org/3/library/stdtypes.html#str.encode - "Return an encoded version of the string as a bytes object")

**Comment by tomvanderlee** [comment] 2016-01-30 16:15
Found more info on the topic: https://docs.python.org/3/howto/pyporting.html#text-versus-binary-data

I will try to make a patch for it.

**Comment by tomvanderlee** [comment] 2016-01-30 16:21
I just wonder @sivel, why is it even encoded like that?

**Comment by sivel** [comment] 2016-01-30 17:57
It will be fixed in a future version. It is already solved in another branch that I have.

**Closed by sivel** 2016-01-30 17:57 UTC
Labels: bug

**Comment by tomvanderlee** [comment] 2016-01-30 18:03
Allright, thanks!
