### ISSUE TITLE
Sharing returnes empty page (0.png)

### ISSUE THREAD

**Issue by yannismate** [sivel/speedtest-cli#522] opened 2018-06-25 20:56 UTC
Version: latest, cloned 1 minute ago
Command: `speedtest-cli  --share`  
Results: `Hosted by LeaseWeb (Frankfurt) [0.49 km]: 1.558 ms`  
`Download: 3393.58 Mbit/s`  
`Upload: 1182.35 Mbit/s`  
`Share results: http://www.speedtest.net/result/0.png`

**Comment by sivel** [comment] 2018-06-25 20:57
Duplicate of https://github.com/sivel/speedtest-cli/issues/482

**Closed by sivel** 2018-06-25 20:57 UTC
