### ISSUE TITLE
Upload speed always show "Upload: 0.00 Mbit/s"

### ISSUE THREAD

**Issue by dotmax** [sivel/speedtest-cli#236] opened 2016-02-21 13:18 UTC
Good morning to all.
in my tests the download speed work as expected, the upload speed always shows 0.00
i've tryied with python 2.7 and with python 3.5 (no change)
whit auto server selection and with the --server option (against 3 different servers)

can you help me please ?
many thanks in advance
best regards.
MAX

**Comment by dotmax** [comment] 2016-03-04 15:37
I've made some tests and found that seems to be an upload timeout issue.
Increasing the default timeout (for my convenience i've modified it to 30 secs in the source code at line 588) work for me.

bye

**Comment by hickford** [comment] 2016-04-29 17:28
I have the same problem.  Please could you reopen the bug?

    Upload: 0.00 Mbit/s

I'm using

    >speedtest-cli --version
    0.3.4

**Comment by dotmax** [comment] 2016-04-29 19:50
Reopened, as requested by mr hickford.

**Comment by monk100** [comment] 2016-04-30 09:18
Same here:

penguin:~ # speedtest
...
Testing download speed........................................
Download: 2.60 Mbit/s
Testing upload speed..................................................
Upload: 0.00 Mbit/s

And it happens with both 3.4 and 2.7
penguin:~ # ls -lta /usr/bin/python*
lrwxrwxrwx 1 root root    9 Mar  6 12:33 /usr/bin/python3 -> python3.4
lrwxrwxrwx 1 root root    9 Nov 16  2014 /usr/bin/python2 -> python2.7

BR, Matthias.

**Comment by WeredPerson** [comment] 2016-05-02 16:45
I was having the same issue, I tried the timeout modification and that did not seem to work, However i manually specified a few different speed test servers and it worked, I did however notice with the timeout on line 588 upped to 30 my upload speeds where showing far lower. Example of the command i used below.  To find the server ID number of a server close to your server you can use the list found here. 

http://www.speedtest.net/speedtest-servers.php

root@Node1:~/speedtest-cli# ./speedtest_cli.py --server 8498

**Comment by sivel** [comment] 2016-05-02 16:48
Does the following branch resolve the issues?

https://github.com/sivel/speedtest-cli/raw/modularize-2/speedtest.py

The timing of upload data is more precise in that version, and will be used in the upcoming release.

**Comment by hickford** [comment] 2016-05-02 17:31
@sivel yes, that copy works for me

    Upload: 0.92 Mbit/s

**Comment by sivel** [comment] 2016-05-02 19:11
Since this is confirmed as resolved in modularize-2 I am going to re-close this.  That branch will become the next major release.

**Closed by sivel** 2016-05-02 19:11 UTC

**Comment by kevincannon** [comment] 2016-05-22 21:07
@sivel - I'm getting the 0.00 Mbit/s message only for download.

I tried the file that you linked to but now i'm getting 0.00 Mbit/s for both upload _and_ dowload.
https://github.com/sivel/speedtest-cli/raw/modularize-2/speedtest.py

I'm running it on a raspberrypi - are there any special requirements for that platform?
