### ISSUE TITLE
Feature Request: Signin

### ISSUE THREAD

**Issue by Josephur** [sivel/speedtest-cli#619] opened 2019-07-16 02:29 UTC
Would be nice to have the ability to sign in to your speedtest.net account before testing, keeps a running history etc.  Shouldn't be too awful difficult to implement?

**Comment by sivel** [comment] 2019-07-22 14:10
Duplicate of https://github.com/sivel/speedtest-cli/issues/607

**Closed by sivel** 2019-07-22 14:10 UTC
