### ISSUE TITLE
Except socket.timeout

### ISSUE THREAD

**Issue by daviddavo** [sivel/speedtest-cli#351] opened 2017-01-05 23:20 UTC
```
[davo@Davo-Arch10 ~]$ speedtest
Retrieving speedtest.net configuration...
Testing from Jazztel (87.218.X.Y)...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "/usr/bin/speedtest", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.1', 'console_scripts', 'speedtest')()
  File "/usr/lib/python3.5/site-packages/speedtest.py", line 1402, in main
    shell()
  File "/usr/lib/python3.5/site-packages/speedtest.py", line 1347, in shell
    speedtest.get_servers(servers)
  File "/usr/lib/python3.5/site-packages/speedtest.py", line 821, in get_servers
    stream = get_response_stream(uh)
  File "/usr/lib/python3.5/site-packages/speedtest.py", line 417, in get_response_stream
    return GzipDecodedResponse(response)
  File "/usr/lib/python3.5/site-packages/speedtest.py", line 296, in __init__
    self.io = IO(response.read())                                                                                                                 
  File "/usr/lib/python3.5/http/client.py", line 461, in read                                                                                     
    s = self._safe_read(self.length)                                                                                                              
  File "/usr/lib/python3.5/http/client.py", line 607, in _safe_read                                                                               
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

Add an "Except" and retry the operation or print an error.

**Comment by sivel** [comment] 2017-01-06 01:08
Duplicate of https://github.com/sivel/speedtest-cli/issues/329

**Closed by sivel** 2017-01-06 01:08 UTC
