### ISSUE TITLE
--mini

### ISSUE THREAD

**Issue by krot4u** [sivel/speedtest-cli#378] opened 2017-03-22 20:01 UTC
Hi!
I have a problem --mini parameter.
```
speedtest-cli --mini "http://<IPadrs>/mini/index-php.html"
Retrieving speedtest.net configuration...
Testing from Rostelecom (<IPadrs>)...
ERROR: Invalid Speedtest Mini Server: http://<IPadrs>/mini/index-php.html
```
On the server side in apache log:
 ```
[22/Mar/2017:19:59:48 +0000] "GET /mini?x=1490212788884. HTTP/1.1" 301 565 "-" "Mozilla/5.0 (Linux; U; 64bit; en-us) Python/2.7.6 (KHTM
[22/Mar/2017:19:59:50 +0000] "GET /mini/?x=1490212788884. HTTP/1.1" 200 2772 "-" "Mozilla/5.0 (Linux; U; 64bit; en-us) Python/2.7.6 (KH
[22/Mar/2017:19:59:50 +0000] "GET /mini/speedtest/upload.php HTTP/1.1" 200 494 "-" "Python-urllib/2.7"
[22/Mar/2017:19:59:50 +0000] "GET /mini/speedtest/upload.asp HTTP/1.1" 200 609 "-" "Python-urllib/2.7"
[22/Mar/2017:19:59:50 +0000] "GET /mini/speedtest/upload.aspx HTTP/1.1" 200 787 "-" "Python-urllib/2.7"
[22/Mar/2017:19:59:50 +0000] "GET /mini/speedtest/upload.jsp HTTP/1.1" 200 799 "-" "Python-urllib/2.7"
```
What could be a problem?

**Comment by sivel** [comment] 2017-03-22 20:11
Duplicate of https://github.com/sivel/speedtest-cli/issues/374

**Closed by sivel** 2017-03-22 20:11 UTC
