### ISSUE TITLE
403 when retrieving server list from China

### ISSUE THREAD

**Issue by phihag** [sivel/speedtest-cli#119] opened 2015-01-07 14:06 UTC
When running speedtest-cli from the network of China Telecom (114.88.*.*), speedtest-cli fails while retrieving the server list:

```
$ ./speedtest_cli.py
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "./speedtest_cli.py", line 692, in <module>
    main()
  File "./speedtest_cli.py", line 686, in main
    speedtest()
  File "./speedtest_cli.py", line 536, in speedtest
    servers = closestServers(config['client'])
  File "./speedtest_cli.py", line 345, in closestServers
    uh = urlopen('http://www.speedtest.net/speedtest-servers-static.php')
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

It works fine from the other locations I have tested. This does **not** seem to be the Chinese GFW, but speedtest.net:

```
$ curl https://www.speedtest.net/speedtest-servers-static.php
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
                <title>403 - Forbidden</title>
        </head>
        <body>
                <h1>403 - Forbidden</h1>
        </body>
</html>
```

There should be a way to use an alternative server list URL.

**Comment by sivel** [comment] 2015-01-16 22:05
Duplicate of #86

**Closed by sivel** 2015-01-16 22:05 UTC
Labels: duplicate
