### ISSUE TITLE
Upload and Download speed shown as 0.00Mb/s on CentOS 7.6 

### ISSUE THREAD

**Issue by SteveHawes** [sivel/speedtest-cli#622] opened 2019-07-27 14:22 UTC
I have just installed this on a DIgitalOcean droplet and am getting the following results:

Retrieving speedtest.net configuration...
Testing from Digital Ocean (134.xxx.xxx.xxx)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Vodafone UK (Acton) [27.24 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed................................................................................................
Upload: 0.00 Mbit/s

Any idea why I am getting no speeds shown?

**Comment by informdev** [comment] 2019-07-28 02:33
I'm experiencing the same issue.

**Comment by sivel** [comment] 2019-07-30 13:51
Duplicate of https://github.com/sivel/speedtest-cli/issues/600

**Closed by sivel** 2019-07-30 13:51 UTC
