### ISSUE TITLE
When --share on speedtests >3,000 Mbit/s, link is broken

### ISSUE THREAD

**Issue by LukeHouge** [sivel/speedtest-cli#547] opened 2018-10-31 04:40 UTC
When the download result for a speedtest is > 3,000 Mbit/s then the resulting share link is always speedtest.net/result/0.png

**Comment by sivel** [comment] 2018-10-31 16:42
Duplicate of https://github.com/sivel/speedtest-cli/issues/241

**Closed by sivel** 2018-10-31 16:42 UTC
