### ISSUE TITLE
--mini cannot be used without internet access

### ISSUE THREAD

**Issue by mildis** [sivel/speedtest-cli#261] opened 2016-05-04 18:12 UTC
I’d like to use speedtest-cli to test speed between internal servers using Speediest Mini.
However, speedtest-cli tries to retrieve configuration from speedtest.net even for internal Mini tests.
As some of the servers used as client do not have internet access, it fails.

--mini option should be usable without internet access.

**Comment by sivel** [comment] 2016-05-04 18:52
Duplicate of https://github.com/sivel/speedtest-cli/pull/182

**Closed by sivel** 2016-05-04 18:52 UTC
