### ISSUE TITLE
Specify Self Hosted Speed Test Server

### ISSUE THREAD

**Issue by rhinomikey** [sivel/speedtest-cli#534] opened 2018-08-01 16:54 UTC
I have been trying to use this tool to automate speed testing and so far it has worked with the normal setup but I have to be able to use an internal self hosted speed test server. The issue is that SpeedTest Mini has been discontinued and currently I have not found a way to add a server to the list to use or specify a non-speedtest.net server. Is there a way that I can add a non speedtest.net server to the list or specify an IP to go to directly?

**Comment by sivel** [comment] 2018-08-01 16:58
duplicate of https://github.com/sivel/speedtest-cli/issues/519

**Closed by sivel** 2018-08-01 16:58 UTC

**Comment by rhinomikey** [comment] 2018-08-01 17:06
I followed it to the code you have to add a non speedtest.net server on the socket branch. I am unsure how to code it into my script tho. How do I add a non speedtest.net server? Or has that not been completed yet? Thanks by the way for the help and quick reply!

**Comment by sivel** [comment] 2018-08-01 17:08
Obviously, based on every description, this app only supports speedtest.net speed tests.  Should you want to use some other non speedtest.net based speed test, you are on your own.
