### ISSUE TITLE
xml.etree.ElementTree.ParseError 

### ISSUE THREAD

**Issue by tterb** [sivel/speedtest-cli#511] opened 2018-05-07 14:16 UTC
I'd been using the program on my Raspberry Pi without issue for the last couple weeks, but last night I started recieving this error everytime I try to run the program.  
I went as far as to reinstall Python 3.6, but there haven't been any changes and it only seems to effect this program.
 
```sh
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/speedtest.py", line 1832, in main
    shell()
  File "/usr/local/lib/python3.6/site-packages/speedtest.py", line 1729, in shell
    secure=args.secure
  File "/usr/local/lib/python3.6/site-packages/speedtest.py", line 1009, in __init__
    self.get_config()
  File "/usr/local/lib/python3.6/site-packages/speedtest.py", line 1065, in get_config
    root = ET.fromstring(''.encode().join(configxml))
  File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 41, column 2
```

Let me know if there's anymore info I can provide.

**Comment by sivel** [comment] 2018-05-07 15:03
Duplicate of #490

**Closed by sivel** 2018-05-07 15:03 UTC
