### ISSUE TITLE
urllib2.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by tiansiyuan** [sivel/speedtest-cli#95] opened 2014-09-12 03:41 UTC
% python speedtest_cli.py
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "speedtest_cli.py", line 692, in <module>
    main()
  File "speedtest_cli.py", line 686, in main
    speedtest()
  File "speedtest_cli.py", line 536, in speedtest
    servers = closestServers(config['client'])
  File "speedtest_cli.py", line 345, in closestServers
    uh = urlopen('http://www.speedtest.net/speedtest-servers-static.php')
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by sivel** [comment] 2015-01-16 22:05
Duplicate of #86

**Closed by sivel** 2015-01-16 22:05 UTC
Labels: duplicate
