### ISSUE TITLE
speedtest always show 0 mbit/s to certain destination server

### ISSUE THREAD

**Issue by hendranata** [sivel/speedtest-cli#634] opened 2019-09-13 02:06 UTC
helo
i face strange issue i guess..
i have update speedtest-cli version to the latest one.
and check speedtest --server 9056 with this result:

[root@jade ~]# ./speedtest-cli --server 9056
Retrieving speedtest.net configuration...
Testing from Rackh Lintas Asia, pt (103.103.175.206)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by LV.Net (Las Vegas, NV) [14601.48 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed................................................................................................
Upload: 0.00 Mbit/s

but when i check another server like this , this is normal
[root@jade ~]# ./speedtest-cli --server 797
Retrieving speedtest.net configuration...
Testing from Rackh Lintas Asia, pt (103.103.175.206)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Biznet Networks (Jakarta) [0.76 km]: 7.684 ms
Testing download speed................................................................................
Download: 785.88 Mbit/s
Testing upload speed................................................................................................
Upload: 561.51 Mbit/s

i am not sure why.. i check to ping the ip server 9056, seems normal no issue.. international connection is okay.. but only speedtest show result like that..

any idea why?

**Comment by sivel** [comment] 2019-09-13 13:44
Duplicate of https://github.com/sivel/speedtest-cli/issues/567

**Closed by sivel** 2019-09-13 13:44 UTC
