### ISSUE TITLE
Result always is 0.00 when using --server parameter

### ISSUE THREAD

**Issue by rafalmasiarek** [sivel/speedtest-cli#604] opened 2019-05-31 09:15 UTC
Hello,
whenever I run a script with a parameter --server , result has always show "0.00/Mbit/s":

`$ ./speedtest-cli --server 4206
Retrieving speedtest.net configuration...
Testing from Hetzner Online GmbH (***.***.***.**)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Orange Polska S.A. (Lodz) [646.48 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed................................................................................................
Upload: 0.00 Mbit/s
`
but normal test without this parametr 
`$ ./speedtest-cli
Retrieving speedtest.net configuration...
Testing from Hetzner Online GmbH (***.***.***.**)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by 10G-Server.com (Nuremberg) [1.12 km]: 2507.742 ms
Testing download speed................................................................................
Download: 876.90 Mbit/s
Testing upload speed................................................................................................
Upload: 471.58 Mbit/s
`

speedtest-cli's version:
`$ ./speedtest-cli --version
speedtest-cli 2.1.1
Python 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
`

**Comment by sivel** [comment] 2019-05-31 14:39
Duplicate of https://github.com/sivel/speedtest-cli/issues/600

**Closed by sivel** 2019-05-31 14:39 UTC
