### ISSUE TITLE
--share doesnt work with speeds over ~5000mbit/s

### ISSUE THREAD

**Issue by Trustmega** [sivel/speedtest-cli#632] opened 2019-08-30 10:01 UTC
With speeds over something around 5000mbit/s download the image link is https://speedtest.net/result/0.png 

Could be related to the speed, could be something else but when i test several times on the same server the only time i get a 0.png is with upload and download speeds over 5000mbit/s

**Comment by sivel** [comment] 2019-08-30 13:09
Duplicate of https://github.com/sivel/speedtest-cli/issues/241

**Closed by sivel** 2019-08-30 13:09 UTC
