### ISSUE TITLE
When measuring speeds above 2Gbps

### ISSUE THREAD

**Issue by nsa2006** [sivel/speedtest-cli#564] opened 2018-12-24 18:18 UTC
Testing download speed................................................................................
Download: 4281.54 Mbit/s
Testing upload speed................................................................................................
Upload: 949.79 Mbit/s

 http://www.speedtest.net/result/0.png

Why such a link?

**Comment by jtl999** [comment] 2018-12-27 02:10
I believe it's a serverside limitation of speedtest.net website

**Comment by sivel** [comment] 2019-01-02 15:13
Duplicate of https://github.com/sivel/speedtest-cli/issues/241

**Closed by sivel** 2019-01-02 15:13 UTC
