### ISSUE TITLE
Balks on XML error

### ISSUE THREAD

**Issue by jamesjryan** [sivel/speedtest-cli#490] opened 2018-03-08 22:51 UTC
Stack trace

```
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/speedtest.py", line 1494, in main
    shell()
  File "/Library/Python/2.7/site-packages/speedtest.py", line 1397, in shell
    speedtest = Speedtest()
  File "/Library/Python/2.7/site-packages/speedtest.py", line 743, in __init__
    self.get_config()
  File "/Library/Python/2.7/site-packages/speedtest.py", line 783, in get_config
    root = ET.fromstring(''.encode().join(configxml))
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 3, column 66
```

**Comment by sivel** [comment] 2018-03-08 23:02
Please try with `--debug` to see what you get.  Also try with `--secure`.  Sometimes speedtest.net has problems and using `--secure` will get you through.

You may want to update to a newer speedtest.py also. You seem to be running an old version.

Regardless, I probably need to address that specific exception.

**Comment by sivel** [comment] 2018-03-09 15:46
Duplicate of https://github.com/sivel/speedtest-cli/issues/491

**Closed by sivel** 2018-03-09 15:46 UTC
